name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Cập nhật lên v3 để tránh lỗi Node 12

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Đảm bảo sử dụng Node 16

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        CI: false
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
